export interface CookieDesign {
    id: string;
    name: string;
    type: 'banner' | 'popup' | 'sidebar' | 'minimal' | 'full-screen';
    position: 'top' | 'bottom' | 'center' | 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
    style: any;
    content: {
        title: string;
        description: string;
        acceptText: string;
        rejectText?: string;
        manageText?: string;
    };
    detailedDescription: string;
}

export const cookieDesigns: CookieDesign[] = [
    {
        id: 'modern-banner-dark',
        name: 'Modern Dark Banner',
        type: 'banner',
        position: 'bottom',
        style: {
            background: 'rgba(18, 18, 18, 0.95)',
            color: '#ffffff',
            backdropFilter: 'blur(10px)',
            borderTop: '1px solid rgba(255, 255, 255, 0.1)',
            padding: '24px',
            borderRadius: '24px 24px 0 0',
            boxShadow: '0 -10px 40px rgba(0, 0, 0, 0.5)',
        },
        content: {
            title: 'Our Cookie Policy',
            description: 'We use cookies to enhance your browsing experience, serve personalized ads or content, and analyze our traffic.',
            acceptText: 'Accept All',
            rejectText: 'Reject All',
            manageText: 'Customize',
        },
        detailedDescription: 'A sleek, professional dark banner common in high-end tech websites. It uses backdrop-blur for a "glass" effect and provides clear CTA buttons for GDPR compliance.',
    },
    {
        id: 'glass-popup-center',
        name: 'Glassmorphism Center Popup',
        type: 'popup',
        position: 'center',
        style: {
            background: 'rgba(255, 255, 255, 0.15)',
            backdropFilter: 'blur(20px)',
            color: '#1a1a1a',
            border: '1px solid rgba(255, 255, 255, 0.3)',
            padding: '40px',
            borderRadius: '32px',
            boxShadow: '0 20px 60px rgba(0, 0, 0, 0.15)',
            maxWidth: '500px',
            width: '90%',
        },
        content: {
            title: 'Cookies & Privacy',
            description: 'Choose how we use cookies to personalize your experience. Your privacy is our top priority.',
            acceptText: 'Allow Selection',
            manageText: 'Privacy Settings',
        },
        detailedDescription: 'A modern UI favorite using glassmorphism. It creates a sense of depth and transparency, often seen in creative portfolios and Apple-inspired interfaces.',
    },
    {
        id: 'minimal-top-bar',
        name: 'Minimalist Top Bar',
        type: 'banner',
        position: 'top',
        style: {
            background: '#ffffff',
            color: '#333333',
            padding: '12px 24px',
            boxShadow: '0 2px 10px rgba(0, 0, 0, 0.05)',
            fontSize: '14px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        content: {
            title: '',
            description: 'This website uses cookies to provide the best possible user experience.',
            acceptText: 'Got it!',
        },
        detailedDescription: 'A classic, non-intrusive design that stays at the top of the page. Minimal consumption of screen real estate makes it ideal for information-heavy sites.',
    },
    {
        id: 'sidebar-right-floating',
        name: 'Floating Sidebar Right',
        type: 'sidebar',
        position: 'bottom-right',
        style: {
            background: '#f8fafc',
            color: '#1e293b',
            padding: '32px',
            borderRadius: '20px',
            margin: '24px',
            boxShadow: '0 10px 30px rgba(0, 0, 0, 0.08)',
            maxWidth: '380px',
            border: '1px solid #e2e8f0',
        },
        content: {
            title: 'Cookie Preferences',
            description: 'We share your cookies data with partners to improve our services. You can change your choice anytime.',
            acceptText: 'Accept & Close',
            rejectText: 'Decline',
            manageText: 'View Details',
        },
        detailedDescription: 'Floating sidebar designs take advantage of white space and are popular in e-commerce and SaaS dashboards.',
    },
    {
        id: 'gradient-neobrutalism',
        name: 'Gradient Neobrutalism',
        type: 'popup',
        position: 'center',
        style: {
            background: 'linear-gradient(135deg, #6366f1 0%, #a855f7 100%)',
            color: '#ffffff',
            padding: '32px',
            borderRadius: '0px',
            border: '4px solid #000000',
            boxShadow: '8px 8px 0px #000000',
            maxWidth: '450px',
        },
        content: {
            title: 'COOKIE ALERT!',
            description: 'WE WANT TO USE COOKIES TO MAKE THIS EXPERIENCE AWESOME.',
            acceptText: 'HELL YEAH!',
            rejectText: 'NO THANKS',
        },
        detailedDescription: 'A bold, high-contrast design trend that rejects traditional UI standards for a more experimental and playful look.',
    },
    {
        id: 'cyberpunk-neon',
        name: 'Cyberpunk Neon',
        type: 'popup',
        position: 'bottom-right',
        style: {
            background: '#000000',
            color: '#00ff41',
            padding: '24px',
            border: '2px solid #00ff41',
            boxShadow: '0 0 15px #00ff41',
            margin: '20px',
            fontFamily: 'monospace',
        },
        content: {
            title: '> INIT_COOKIE_CONSENT',
            description: 'COOKIE_TRACKING: ENABLED | PERSONALIZATION: ENABLED. PROCEED?',
            acceptText: '[ YES ]',
            rejectText: '[ NO ]',
        },
        detailedDescription: 'A futuristic design inspired by 80s computer terminals and sci-fi aesthetic. Perfect for gaming sites or creative studios.',
    },
    {
        id: 'soft-pastel-bottom',
        name: 'Soft Pastel Banner',
        type: 'banner',
        position: 'bottom',
        style: {
            background: '#fff5f5',
            color: '#ff6b6b',
            padding: '20px',
            borderRadius: '20px 20px 0 0',
            boxShadow: '0 -4px 15px rgba(255, 107, 107, 0.1)',
            borderTop: '2px solid #ffa8a8',
        },
        content: {
            title: 'Cookie Treat?',
            description: 'We use cookies to make our site sweeter. By continuing, you agree to our use of cookies.',
            acceptText: 'Yummy!',
            rejectText: 'Not today',
        },
        detailedDescription: 'Uses warm, inviting colors and friendly copy to reduce "banner fatigue" and improve user acceptance rates.',
    },
    {
        id: 'elegant-serif-center',
        name: 'Elegant Serif Modal',
        type: 'popup',
        position: 'center',
        style: {
            background: '#ffffff',
            color: '#1a1a1a',
            padding: '48px',
            borderRadius: '0',
            border: '1px solid #d1d5db',
            fontFamily: 'serif',
            textAlign: 'center',
            maxWidth: '600px',
            boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        },
        content: {
            title: 'A Moment for Cookies',
            description: 'We invite you to review our updated cookie protocols designed to safeguard your digital presence.',
            acceptText: 'I Accept',
            rejectText: 'Decline',
        },
        detailedDescription: 'A sophisticated design often used by luxury brands and high-end publications to maintain a premium brand image during legal disclosures.',
    },
    {
        id: 'retro-windows-95',
        name: 'Retro Windows 95',
        type: 'popup',
        position: 'center',
        style: {
            background: '#c0c0c0',
            color: '#000000',
            borderTop: '2px solid #ffffff',
            borderLeft: '2px solid #ffffff',
            borderRight: '2px solid #808080',
            borderBottom: '2px solid #808080',
            padding: '4px',
            maxWidth: '400px',
        },
        content: {
            title: 'Cookie.exe Configuration',
            description: 'Warning: This site requires cookies to operate correctly. Would you like to enable them now?',
            acceptText: 'OK',
            rejectText: 'Cancel',
        },
        detailedDescription: 'A nostalgic UI that mimics the classic Windows 95 interface, popular for retro-gaming sites or unique brand experiences.',
    },
    {
        id: 'high-contrast-accessibility',
        name: 'High Contrast (A11y)',
        type: 'banner',
        position: 'bottom',
        style: {
            background: '#ffff00',
            color: '#000000',
            padding: '24px',
            border: '4px solid #000000',
            fontWeight: '900',
            fontSize: '18px',
        },
        content: {
            title: 'COOKIES IN USE',
            description: 'THIS SITE USES COOKIES FOR ESSENTIAL FUNCTIONS.',
            acceptText: 'I UNDERSTAND',
        },
        detailedDescription: 'Prioritizes accessibility and readability above all else, ensuring users with visual impairments can easily interact with the consent form.',
    },
    {
        id: 'minimal-bottom-right-pill',
        name: 'Minimalist Pill',
        type: 'minimal',
        position: 'bottom-right',
        style: {
            background: '#ffffff',
            color: '#1e293b',
            padding: '12px 20px',
            borderRadius: '100px',
            margin: '24px',
            boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
            display: 'flex',
            alignItems: 'center',
            gap: '16px',
            border: '1px solid #e2e8f0',
        },
        content: {
            title: '',
            description: 'We use cookies.',
            acceptText: 'OK',
            manageText: 'Settings',
        },
        detailedDescription: 'A compact, non-intrusive pill-shaped banner that stays out of the user\'s way while remaining easily accessible.',
    },
    {
        id: 'vibrant-blue-gradient',
        name: 'Vibrant Blue Wave',
        type: 'banner',
        position: 'bottom',
        style: {
            background: 'linear-gradient(90deg, #1e3a8a 0%, #3b82f6 100%)',
            color: '#ffffff',
            padding: '30px',
            boxShadow: '0 -10px 30px rgba(59, 130, 246, 0.3)',
        },
        content: {
            title: 'Enhance Your Cookies Experience',
            description: 'Our cookies help provide a faster and more specialized browsing experience.',
            acceptText: 'Yes, please!',
            rejectText: 'Skip',
        },
        detailedDescription: 'Uses energetic gradients and friendly copy to create a positive association with cookie acceptance.',
    },
    {
        id: 'dark-transparent-sidebar',
        name: 'Glass Sidebar Left',
        type: 'sidebar',
        position: 'bottom-left',
        style: {
            background: 'rgba(0, 0, 0, 0.7)',
            backdropFilter: 'blur(12px)',
            color: '#cbd5e1',
            padding: '24px',
            borderRadius: '0 20px 20px 0',
            border: '1px solid rgba(255, 255, 255, 0.1)',
            maxWidth: '320px',
        },
        content: {
            title: 'Cookies & Data Control',
            description: 'You are in control of your cookies. Choose your preferences below.',
            acceptText: 'Allow All',
            manageText: 'Manage',
        },
        detailedDescription: 'A professional-looking sidebar that uses transparency to avoid obscuring page content completely.',
    },
    {
        id: 'sketch-hand-drawn',
        name: 'Hand-Drawn Sketch',
        type: 'popup',
        position: 'center',
        style: {
            background: '#fffdf2',
            color: '#2d3436',
            padding: '32px',
            borderRadius: '15px 50px 30px 5px',
            border: '3px solid #000000',
            fontFamily: 'cursive',
            maxWidth: '450px',
            boxShadow: '10px 10px 0px rgba(0,0,0,0.1)',
        },
        content: {
            title: 'Cookie crumbs?',
            description: 'Mind if we leave a few cookies around to help us remember you?',
            acceptText: 'Sure!',
            rejectText: 'Nah',
        },
        detailedDescription: 'A creative, playful design for illustrators, artists, or boutique brands.',
    },
    {
        id: 'corporate-blue-legal',
        name: 'Standard Corporate',
        type: 'banner',
        position: 'bottom',
        style: {
            background: '#f1f5f9',
            color: '#334155',
            padding: '16px 40px',
            borderTop: '3px solid #2563eb',
            fontSize: '13px',
        },
        content: {
            title: 'Legal Notice: Cookies',
            description: 'This website utilizes cookies in accordance with GDPR and international privacy standards.',
            acceptText: 'I Accept Terms',
            manageText: 'Read Disclosure',
        },
        detailedDescription: 'A strictly professional and legalistic design, minimizing flair to convey seriousness and compliance.',
    },
    {
        id: 'playful-floating-cookies',
        name: 'Playful Floating Shapes',
        type: 'minimal',
        position: 'bottom-left',
        style: {
            background: '#faf5ff',
            color: '#7e22ce',
            padding: '20px',
            borderRadius: '30px',
            margin: '20px',
            border: '2px dashed #a855f7',
            boxShadow: '0 8px 30px rgba(168, 85, 247, 0.15)',
        },
        content: {
            title: 'Cookie Time! 🍪',
            description: 'We use cookies 🍪 to make things better. Cool with that?',
            acceptText: 'Accept! 🍪',
        },
        detailedDescription: 'Uses emojis and a dashed border to create a friendly, non-corporate vibe.',
    },
    {
        id: 'fullscreen-takeover',
        name: 'Full-Screen Priority',
        type: 'full-screen',
        position: 'center',
        style: {
            background: '#000000',
            color: '#ffffff',
            padding: '60px',
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            height: '100vh',
            width: '100vw',
            position: 'fixed',
            top: 0,
            left: 0,
            zIndex: 10000,
        },
        content: {
            title: 'Your Privacy is Our Priority',
            description: 'Before you enter, please acknowledge our cookies data collection practices. We value your trust.',
            acceptText: 'I Agree & Enter Site',
            manageText: 'Privacy Policy',
        },
        detailedDescription: 'A rare but high-impact design that requires user interaction before any content can be viewed. Used for strictly regulated industries.',
    },
    {
        id: 'luxury-gold-accent',
        name: 'Luxury Gold Trim',
        type: 'sidebar',
        position: 'bottom-right',
        style: {
            background: '#1a1a1a',
            color: '#d4af37',
            padding: '30px',
            borderLeft: '2px solid #d4af37',
            borderRadius: '8px 0 0 8px',
            boxShadow: '0 0 40px rgba(0,0,0,0.8)',
        },
        content: {
            title: 'Bespoke Cookies Experience',
            description: 'Allow us to tailor your journey with refined cookie selection.',
            acceptText: 'Indulge',
            manageText: 'Preferences',
        },
        detailedDescription: 'Designed for high-end fashion and lifestyle brands, emphasizing exclusivity and detail.',
    },
    {
        id: 'delayed-slow-slide',
        name: 'Delayed Slow-Slide Banner',
        type: 'banner',
        position: 'bottom',
        style: {
            background: '#ffffff',
            color: '#000000',
            padding: '24px',
            borderTop: '1px solid #e2e8f0',
            boxShadow: '0 -4px 20px rgba(0, 0, 0, 0.05)',
            animation: 'slowSlideUp 1.5s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        },
        content: {
            title: 'Wait, We Have Cookies!',
            description: 'We waited for your page to load before showing you this cookies consent form. We use cookies to improve your experience.',
            acceptText: 'Accept All',
            manageText: 'Settings',
        },
        detailedDescription: 'Simulates a network-idle load by waiting 2 seconds before sliding up slowly from the bottom. Ideal for reducing initial page load distraction.',
    }
];
