export interface CookieDesign {
    id: string;
    name: string;
    type: 'banner' | 'popup' | 'sidebar' | 'minimal' | 'full-screen';
    position: 'top' | 'bottom' | 'center' | 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
    style: any;
    content: {
        title: string;
        description: string;
        acceptText: string;
        rejectText?: string;
        manageText?: string;
    };
    detailedDescription: string;
}

/*
 * The gallery of consent-banner treatments.
 *
 * Each entry keeps the structure that makes it recognisable — the glass blur,
 * the brutalist offset shadow, the Windows 95 bevel, the terminal monospace —
 * but every colour now resolves to a Pastel Premium token and the type sits on
 * the app's Fraunces/Manrope pairing. The two exceptions are called out where
 * they occur: the accessibility fixture keeps its maximum-contrast pair, and
 * the monospace and cursive faces are the identity of their designs.
 */
export const cookieDesigns: CookieDesign[] = [
    {
        id: 'modern-banner-dark',
        name: 'Modern Dark Banner',
        type: 'banner',
        position: 'bottom',
        style: {
            background: 'color-mix(in srgb, var(--color-neutral-900) 95%, transparent)',
            color: 'var(--color-on-dark)',
            fontFamily: 'var(--font-body)',
            backdropFilter: 'blur(10px)',
            borderTop: '1px solid color-mix(in srgb, var(--color-on-dark) 14%, transparent)',
            padding: '24px',
            borderRadius: '24px 24px 0 0',
            boxShadow: '0 -10px 40px color-mix(in srgb, var(--color-neutral-900) 45%, transparent)',
        },
        content: {
            title: 'Our Cookie Policy',
            description: 'We use cookies to enhance your browsing experience, serve personalized ads or content, and analyze our traffic.',
            acceptText: 'Accept All',
            rejectText: 'Reject All',
            manageText: 'Customize',
        },
        detailedDescription: 'A sleek, professional dark banner common in high-end tech websites. It uses backdrop-blur for a "glass" effect and provides clear CTA buttons for GDPR compliance.',
    },
    {
        id: 'glass-popup-center',
        name: 'Glassmorphism Center Popup',
        type: 'popup',
        position: 'center',
        style: {
            background: 'color-mix(in srgb, var(--color-surface-raised) 22%, transparent)',
            backdropFilter: 'blur(20px)',
            color: 'var(--color-text)',
            fontFamily: 'var(--font-body)',
            border: '1px solid color-mix(in srgb, var(--color-surface-raised) 40%, transparent)',
            padding: '40px',
            borderRadius: '32px',
            boxShadow: '0 20px 60px color-mix(in srgb, var(--color-text) 18%, transparent)',
            maxWidth: '500px',
            width: '90%',
        },
        content: {
            title: 'Cookies & Privacy',
            description: 'Choose how we use cookies to personalize your experience. Your privacy is our top priority.',
            acceptText: 'Allow Selection',
            manageText: 'Privacy Settings',
        },
        detailedDescription: 'A modern UI favorite using glassmorphism. It creates a sense of depth and transparency, often seen in creative portfolios and Apple-inspired interfaces.',
    },
    {
        id: 'minimal-top-bar',
        name: 'Minimalist Top Bar',
        type: 'banner',
        position: 'top',
        style: {
            background: 'var(--color-surface-raised)',
            color: 'var(--color-neutral-800)',
            fontFamily: 'var(--font-body)',
            padding: '12px 24px',
            boxShadow: '0 2px 10px color-mix(in srgb, var(--color-text) 8%, transparent)',
            fontSize: '14px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        content: {
            title: '',
            description: 'This website uses cookies to provide the best possible user experience.',
            acceptText: 'Got it!',
        },
        detailedDescription: 'A classic, non-intrusive design that stays at the top of the page. Minimal consumption of screen real estate makes it ideal for information-heavy sites.',
    },
    {
        id: 'sidebar-right-floating',
        name: 'Floating Sidebar Right',
        type: 'sidebar',
        position: 'bottom-right',
        style: {
            background: 'var(--color-surface)',
            color: 'var(--color-text)',
            fontFamily: 'var(--font-body)',
            padding: '32px',
            borderRadius: '20px',
            margin: '24px',
            boxShadow: '0 10px 30px color-mix(in srgb, var(--color-text) 10%, transparent)',
            maxWidth: '380px',
            border: '1px solid var(--color-divider)',
        },
        content: {
            title: 'Cookie Preferences',
            description: 'We share your cookies data with partners to improve our services. You can change your choice anytime.',
            acceptText: 'Accept & Close',
            rejectText: 'Decline',
            manageText: 'View Details',
        },
        detailedDescription: 'Floating sidebar designs take advantage of white space and are popular in e-commerce and SaaS dashboards.',
    },
    {
        id: 'gradient-neobrutalism',
        name: 'Gradient Neobrutalism',
        type: 'popup',
        position: 'center',
        style: {
            background: 'linear-gradient(135deg, var(--color-accent-700) 0%, var(--color-sky-600) 100%)',
            color: 'var(--color-on-dark)',
            fontFamily: 'var(--font-body)',
            padding: '32px',
            borderRadius: '0px',
            border: '4px solid var(--color-text)',
            boxShadow: '8px 8px 0px var(--color-text)',
            maxWidth: '450px',
        },
        content: {
            title: 'COOKIE ALERT!',
            description: 'WE WANT TO USE COOKIES TO MAKE THIS EXPERIENCE AWESOME.',
            acceptText: 'HELL YEAH!',
            rejectText: 'NO THANKS',
        },
        detailedDescription: 'A bold, high-contrast design trend that rejects traditional UI standards for a more experimental and playful look.',
    },
    {
        id: 'cyberpunk-neon',
        name: 'Cyberpunk Neon',
        type: 'popup',
        position: 'bottom-right',
        style: {
            background: 'var(--color-accent-900)',
            color: 'var(--color-sky-400)',
            padding: '24px',
            border: '2px solid var(--color-sky-400)',
            boxShadow: '0 0 15px color-mix(in srgb, var(--color-sky-400) 60%, transparent)',
            margin: '20px',
            // Monospace is this design's whole point, so it keeps its own face.
            fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        },
        content: {
            title: '> INIT_COOKIE_CONSENT',
            description: 'COOKIE_TRACKING: ENABLED | PERSONALIZATION: ENABLED. PROCEED?',
            acceptText: '[ YES ]',
            rejectText: '[ NO ]',
        },
        detailedDescription: 'A futuristic design inspired by 80s computer terminals and sci-fi aesthetic. Perfect for gaming sites or creative studios.',
    },
    {
        id: 'soft-pastel-bottom',
        name: 'Soft Pastel Banner',
        type: 'banner',
        position: 'bottom',
        style: {
            background: 'var(--color-accent-2-100)',
            color: 'var(--color-accent-2-900)',
            fontFamily: 'var(--font-body)',
            padding: '20px',
            borderRadius: '20px 20px 0 0',
            boxShadow: '0 -4px 15px color-mix(in srgb, var(--color-accent-2-500) 22%, transparent)',
            borderTop: '2px solid var(--color-accent-2-400)',
        },
        content: {
            title: 'Cookie Treat?',
            description: 'We use cookies to make our site sweeter. By continuing, you agree to our use of cookies.',
            acceptText: 'Yummy!',
            rejectText: 'Not today',
        },
        detailedDescription: 'Uses warm, inviting colors and friendly copy to reduce "banner fatigue" and improve user acceptance rates.',
    },
    {
        id: 'elegant-serif-center',
        name: 'Elegant Serif Modal',
        type: 'popup',
        position: 'center',
        style: {
            background: 'var(--color-surface-raised)',
            color: 'var(--color-text)',
            padding: '48px',
            borderRadius: '0',
            border: '1px solid var(--color-divider-strong)',
            // The luxury register this design is after is exactly what the
            // system's display serif is for.
            fontFamily: 'var(--font-display)',
            textAlign: 'center',
            maxWidth: '600px',
            boxShadow: '0 25px 50px -12px color-mix(in srgb, var(--color-text) 28%, transparent)',
        },
        content: {
            title: 'A Moment for Cookies',
            description: 'We invite you to review our updated cookie protocols designed to safeguard your digital presence.',
            acceptText: 'I Accept',
            rejectText: 'Decline',
        },
        detailedDescription: 'A sophisticated design often used by luxury brands and high-end publications to maintain a premium brand image during legal disclosures.',
    },
    {
        id: 'retro-windows-95',
        name: 'Retro Windows 95',
        type: 'popup',
        position: 'center',
        style: {
            background: 'var(--color-neutral-300)',
            color: 'var(--color-text)',
            fontFamily: 'var(--font-body)',
            borderTop: '2px solid var(--color-neutral-100)',
            borderLeft: '2px solid var(--color-neutral-100)',
            borderRight: '2px solid var(--color-neutral-600)',
            borderBottom: '2px solid var(--color-neutral-600)',
            padding: '4px',
            maxWidth: '400px',
        },
        content: {
            title: 'Cookie.exe Configuration',
            description: 'Warning: This site requires cookies to operate correctly. Would you like to enable them now?',
            acceptText: 'OK',
            rejectText: 'Cancel',
        },
        detailedDescription: 'A nostalgic UI that mimics the classic Windows 95 interface, popular for retro-gaming sites or unique brand experiences.',
    },
    {
        id: 'high-contrast-accessibility',
        name: 'High Contrast (A11y)',
        type: 'banner',
        position: 'bottom',
        style: {
            // Deliberately NOT themed. This fixture exists to demonstrate a
            // maximum-contrast pair (19.6:1); pastel yellow on pastel dark blue
            // would drop it to roughly 8:1 and defeat the point of the design.
            background: '#ffff00',
            color: '#000000',
            padding: '24px',
            border: '4px solid #000000',
            fontFamily: 'var(--font-body)',
            fontWeight: '900',
            fontSize: '18px',
        },
        content: {
            title: 'COOKIES IN USE',
            description: 'THIS SITE USES COOKIES FOR ESSENTIAL FUNCTIONS.',
            acceptText: 'I UNDERSTAND',
        },
        detailedDescription: 'Prioritizes accessibility and readability above all else, ensuring users with visual impairments can easily interact with the consent form.',
    },
    {
        id: 'minimal-bottom-right-pill',
        name: 'Minimalist Pill',
        type: 'minimal',
        position: 'bottom-right',
        style: {
            background: 'var(--color-surface-raised)',
            color: 'var(--color-text)',
            fontFamily: 'var(--font-body)',
            padding: '12px 20px',
            borderRadius: '100px',
            margin: '24px',
            boxShadow: '0 4px 20px color-mix(in srgb, var(--color-text) 12%, transparent)',
            display: 'flex',
            alignItems: 'center',
            gap: '16px',
            border: '1px solid var(--color-divider)',
        },
        content: {
            title: '',
            description: 'We use cookies.',
            acceptText: 'OK',
            manageText: 'Settings',
        },
        detailedDescription: 'A compact, non-intrusive pill-shaped banner that stays out of the user\'s way while remaining easily accessible.',
    },
    {
        id: 'vibrant-blue-gradient',
        name: 'Vibrant Blue Wave',
        type: 'banner',
        position: 'bottom',
        style: {
            background: 'linear-gradient(90deg, var(--color-accent-900) 0%, var(--color-sky-600) 100%)',
            color: 'var(--color-on-dark)',
            fontFamily: 'var(--font-body)',
            padding: '30px',
            boxShadow: '0 -10px 30px color-mix(in srgb, var(--color-sky-600) 34%, transparent)',
        },
        content: {
            title: 'Enhance Your Cookies Experience',
            description: 'Our cookies help provide a faster and more specialized browsing experience.',
            acceptText: 'Yes, please!',
            rejectText: 'Skip',
        },
        detailedDescription: 'Uses energetic gradients and friendly copy to create a positive association with cookie acceptance.',
    },
    {
        id: 'dark-transparent-sidebar',
        name: 'Glass Sidebar Left',
        type: 'sidebar',
        position: 'bottom-left',
        style: {
            background: 'color-mix(in srgb, var(--color-neutral-900) 78%, transparent)',
            backdropFilter: 'blur(12px)',
            color: 'var(--color-neutral-400)',
            fontFamily: 'var(--font-body)',
            padding: '24px',
            borderRadius: '0 20px 20px 0',
            border: '1px solid color-mix(in srgb, var(--color-on-dark) 14%, transparent)',
            maxWidth: '320px',
        },
        content: {
            title: 'Cookies & Data Control',
            description: 'You are in control of your cookies. Choose your preferences below.',
            acceptText: 'Allow All',
            manageText: 'Manage',
        },
        detailedDescription: 'A professional-looking sidebar that uses transparency to avoid obscuring page content completely.',
    },
    {
        id: 'sketch-hand-drawn',
        name: 'Hand-Drawn Sketch',
        type: 'popup',
        position: 'center',
        style: {
            background: 'var(--color-accent-2-100)',
            color: 'var(--color-text)',
            padding: '32px',
            borderRadius: '15px 50px 30px 5px',
            border: '3px solid var(--color-text)',
            // The hand-drawn face is this design's identity, so it stays.
            fontFamily: 'cursive',
            maxWidth: '450px',
            boxShadow: '10px 10px 0px color-mix(in srgb, var(--color-text) 12%, transparent)',
        },
        content: {
            title: 'Cookie crumbs?',
            description: 'Mind if we leave a few cookies around to help us remember you?',
            acceptText: 'Sure!',
            rejectText: 'Nah',
        },
        detailedDescription: 'A creative, playful design for illustrators, artists, or boutique brands.',
    },
    {
        id: 'corporate-blue-legal',
        name: 'Standard Corporate',
        type: 'banner',
        position: 'bottom',
        style: {
            background: 'var(--color-neutral-200)',
            color: 'var(--color-neutral-800)',
            fontFamily: 'var(--font-body)',
            padding: '16px 40px',
            borderTop: '3px solid var(--color-accent)',
            fontSize: '13px',
        },
        content: {
            title: 'Legal Notice: Cookies',
            description: 'This website utilizes cookies in accordance with GDPR and international privacy standards.',
            acceptText: 'I Accept Terms',
            manageText: 'Read Disclosure',
        },
        detailedDescription: 'A strictly professional and legalistic design, minimizing flair to convey seriousness and compliance.',
    },
    {
        id: 'playful-floating-cookies',
        name: 'Playful Floating Shapes',
        type: 'minimal',
        position: 'bottom-left',
        style: {
            background: 'var(--color-sky-100)',
            color: 'var(--color-sky-800)',
            fontFamily: 'var(--font-body)',
            padding: '20px',
            borderRadius: '30px',
            margin: '20px',
            border: '2px dashed var(--color-sky-500)',
            boxShadow: '0 8px 30px color-mix(in srgb, var(--color-sky-600) 22%, transparent)',
        },
        content: {
            title: 'Cookie Time! 🍪',
            description: 'We use cookies 🍪 to make things better. Cool with that?',
            acceptText: 'Accept! 🍪',
        },
        detailedDescription: 'Uses emojis and a dashed border to create a friendly, non-corporate vibe.',
    },
    {
        id: 'fullscreen-takeover',
        name: 'Full-Screen Priority',
        type: 'full-screen',
        position: 'center',
        style: {
            background: 'var(--color-accent-900)',
            color: 'var(--color-on-dark)',
            fontFamily: 'var(--font-body)',
            padding: '60px',
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            height: '100vh',
            width: '100vw',
            position: 'fixed',
            top: 0,
            left: 0,
            zIndex: 10000,
        },
        content: {
            title: 'Your Privacy is Our Priority',
            description: 'Before you enter, please acknowledge our cookies data collection practices. We value your trust.',
            acceptText: 'I Agree & Enter Site',
            manageText: 'Privacy Policy',
        },
        detailedDescription: 'A rare but high-impact design that requires user interaction before any content can be viewed. Used for strictly regulated industries.',
    },
    {
        id: 'luxury-gold-accent',
        name: 'Luxury Gold Trim',
        type: 'sidebar',
        position: 'bottom-right',
        style: {
            background: 'var(--color-neutral-900)',
            color: 'var(--color-accent-2-400)',
            // Luxury reads as the display serif here, not a second gold.
            fontFamily: 'var(--font-display)',
            padding: '30px',
            borderLeft: '2px solid var(--color-accent-2-400)',
            borderRadius: '8px 0 0 8px',
            boxShadow: '0 0 40px color-mix(in srgb, var(--color-neutral-900) 70%, transparent)',
        },
        content: {
            title: 'Bespoke Cookies Experience',
            description: 'Allow us to tailor your journey with refined cookie selection.',
            acceptText: 'Indulge',
            manageText: 'Preferences',
        },
        detailedDescription: 'Designed for high-end fashion and lifestyle brands, emphasizing exclusivity and detail.',
    },
    {
        id: 'delayed-slow-slide',
        name: 'Delayed Slow-Slide Banner',
        type: 'banner',
        position: 'bottom',
        style: {
            background: 'var(--color-surface-raised)',
            color: 'var(--color-text)',
            fontFamily: 'var(--font-body)',
            padding: '24px',
            borderTop: '1px solid var(--color-divider)',
            boxShadow: '0 -4px 20px color-mix(in srgb, var(--color-text) 8%, transparent)',
            animation: 'slowSlideUp 1.5s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        },
        content: {
            title: 'Wait, We Have Cookies!',
            description: 'We waited for your page to load before showing you this cookies consent form. We use cookies to improve your experience.',
            acceptText: 'Accept All',
            manageText: 'Settings',
        },
        detailedDescription: 'Simulates a network-idle load by waiting 2 seconds before sliding up slowly from the bottom. Ideal for reducing initial page load distraction.',
    }
];
